# Generated by Django 4.0.2 on 2022-02-17 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_task_tasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
